package com.indexforge.search.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Entity representing an animal document in the search index.
 * Source of truth is PostgreSQL. This service only reads from the database.
 *
 * The database contains 196 animal documents with:
 * - Structured fields (name, diet, habitat, etc.)
 * - Wikipedia summaries
 * - 384-dimensional embedding vectors (populated by external pipeline)
 */
@Entity
@Table(name = "animals")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Animal {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name", nullable = false, length = 255)
    private String name;

    @Column(name = "height", length = 100)
    private String height;

    @Column(name = "weight", length = 100)
    private String weight;

    @Column(name = "color", length = 255)
    private String color;

    @Column(name = "lifespan", length = 100)
    private String lifespan;

    @Column(name = "diet", length = 255)
    private String diet;

    @Column(name = "habitat", columnDefinition = "TEXT")
    private String habitat;

    @Column(name = "predators", columnDefinition = "TEXT")
    private String predators;

    @Column(name = "average_speed", length = 100)
    private String averageSpeed;

    @Column(name = "countries_found", columnDefinition = "TEXT")
    private String countriesFound;

    @Column(name = "family", length = 255)
    private String family;

    @Column(name = "conservation_status", length = 100)
    private String conservationStatus;

    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    @Column(name = "wikipedia_summary", columnDefinition = "TEXT")
    private String wikipediaSummary;

    @Column(name = "search_document", columnDefinition = "TEXT")
    private String searchDocument;

    /**
     * Embedding vector for semantic similarity search.
     * Stored as pgvector type in PostgreSQL (384 dimensions).
     * Generated by the external data pipeline using all-MiniLM-L6-v2 model.
     * IVFFlat index exists on this column for approximate nearest neighbor search.
     */
    @Column(name = "embedding", columnDefinition = "vector(384)")
    private String embedding;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}